### ISSUE TITLE
https://github.com/google/web-starter-kit

### ISSUE THREAD

**Issue by happypeter** [happypeter/go-responsive#4]
https://github.com/google/web-starter-kit

这个要研究一下

**Comment by billie66** [comment]
- It’s multi-device responsive
- Component style-guide
- Cross device synchronization
- Live reload of the browser without any extra components
- Ultra high performance with build tasks
- Integrated HTTP server
- PageSpeed reports
- Powered by SASS

**Comment by billie66** [comment]
http://techcrunch.com/2014/06/19/google-launches-web-starter-kit-a-boilerplate-for-multi-screen-web-development/

http://creativecoon.com/google-web-starter-kit-vs-twitter-bootstrap-3/

https://github.com/dszymczuk/twitter-bootstrap-web-starter-kit/blob/master/app/index.html

**Comment by billie66** [comment]
在虚拟机中使用了一下这个工具，应该说搭建了一个前端开发环境更确切些，它自带 HTTP server，并使用 gulp.js 来自动化任务，gulp.js 依赖于 node.js，所以首先要安装 node.js。另外，web-starter-kit 使用 sass，所以需要 ruby 和 sass gem。
