### ISSUE TITLE
google web fundamentals

### ISSUE THREAD

**Issue by billie66** [happypeter/go-responsive#6]
https://developers.google.com/web/fundamentals/layouts/rwd-fundamentals/?hl=en

**Comment by happypeter** [comment]
基本的思路和咱们写到书里的差不多，也是 mobile first

**Comment by happypeter** [comment]
做这个 quiz 的时候：http://udacity.github.io/RWDF-samples/quizzes/custom-device-quiz.html

设置好之后，还是报错，cmd-++/-- 一下就好了。

**Comment by happypeter** [comment]
https://www.udacity.com/course/viewer#!/c-ud893/l-3494350031/m-3495129024

DIP: device independent pixel

**Comment by happypeter** [comment]
>Take a look at the fourth answer. Without a viewport set, your content may be scaled by the browser.


https://www.udacity.com/course/viewer#!/c-ud893/l-3494350031/e-3566519000/m-3565149257

现在知道为啥要设置 viewport 了

**Comment by happypeter** [comment]
https://www.udacity.com/course/viewer#!/c-ud893/l-3494350031/m-3576408597

     <meta name="viewport" content="width=device-width, initial-scale=1" />

的详细介绍在这里。

**Comment by happypeter** [comment]
https://www.udacity.com/course/viewer#!/c-ud893/l-3494350031/e-3557629322/m-3525430549

> 一个按钮最小要 40 个像素，最佳的是 48 个像素，因为咱们手指大概就是那么粗

**Comment by happypeter** [comment]
为何要 mobile first ：https://www.udacity.com/course/viewer#!/c-ud893/l-3494350031/m-3473199720

很有料

**Comment by happypeter** [comment]
https://www.udacity.com/course/viewer#!/c-ud893/l-3533879576/m-3492369998

如何设置断点

> we should not set break points at all, we should find them

**Comment by happypeter** [comment]
https://www.udacity.com/course/viewer#!/c-ud893/l-3533879576/m-3556399035

flexbox 和 fluid grid 都是和布局相关的。就在上面链接前后的几个视频中介绍了。

**Comment by happypeter** [comment]
https://www.udacity.com/course/viewer#!/c-ud893/l-3561069759/m-3518589214

column drop 这些名词很重要

**Comment by happypeter** [comment]
mostly fluid 策略是我自己最长用到的：https://www.udacity.com/course/viewer#!/c-ud893/l-3561069759/e-3529819408/m-3571808936

**Comment by happypeter** [comment]
各个章节都在我的书里面引用了。
